process:
  frequency: 1
  requireRegister: false
  log_latency_flag: true
  latency_logging_path: "logs/"
  aggregator_host: "127.0.0.1"
  aggregator_port: 12345
system:
  frequency: 1
  requireRegister: false
  latency_logging_path: "logs/"
  log_latency_flag: true
  aggregator_host: "127.0.0.1"
  aggregator_port: 12345
exporter:
  host: "127.0.0.1"
  port: 8000
  node_aggregator:
    host: "127.0.0.1"
    port: 12345
    database_path: "/db.csv"
    query_method: "GET"
    backlog_number: 5
    socket_package_size: 4096
    data_separator: "dot"
    unit_conversion:
      cpu: 
        usage:
          milicpu: 1
          cputime: 2
          percentage: 3
      gpu: 
        usage: 
          percentage: 1
      mem: 
        Gb: 1
        Mb: 2
        Kb: 3
      frequency:
        GHz: 1
        MHz: 2
