client:
  username: aaltosea1
  instance_name: data_handling01
  stage_id: gateway
  functionality: REST
  application_name: test
  role: ml
connector:
  - name: amqp_connector
    connector_class: AMQP
    config:
      end_point: localhost
      exchange_name: test_qoa4ml
      exchange_type: topic
      out_routing_key: test.client1
